name: lightning
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alabaster=0.7.13=pyhd8ed1ab_0
  - alsa-lib=1.2.8=h166bdaf_0
  - arrow=1.2.3=pyhd8ed1ab_0
  - astroid=2.15.5=py38h578d9bd_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.1.0=pyh71513ae_1
  - autopep8=2.0.2=pyhd8ed1ab_0
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=23.3.0=py38h578d9bd_1
  - bleach=6.0.0=pyhd8ed1ab_0
  - boost=1.78.0=py38h4e30db6_4
  - boost-cpp=1.78.0=h6582d0a_3
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - cairo=1.16.0=hbbf8b49_1016
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h4a40e3a_3
  - chardet=5.1.0=py38h578d9bd_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.0.7=py38hfbd4bf9_0
  - cookiecutter=2.1.1=pyh6c4a22f_0
  - cryptography=41.0.1=py38hcdda232_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.7=py38h8dc9893_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20230430=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - docstring-to-markdown=0.12=pyhd8ed1ab_0
  - docutils=0.20.1=py38h578d9bd_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - flake8=6.0.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.4=py38h01eb140_0
  - freetype=2.12.1=hca18f0e_1
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - glib=2.76.3=hfc55251_0
  - glib-tools=2.76.3=hfc55251_0
  - graphite2=1.3.13=h58526e2_1001
  - greenlet=2.0.2=py38h17151c0_1
  - gst-plugins-base=1.22.3=h938bd60_1
  - gstreamer=1.22.3=h977cf35_1
  - harfbuzz=7.3.0=hdb3a94d_0
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.23.1=pyh210e3f2_0
  - ipython=8.4.0=py38h578d9bd_0
  - ipython_genutils=0.2.0=py_1
  - isort=5.12.0=pyhd8ed1ab_1
  - jaraco.classes=3.2.3=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jellyfish=0.9.0=py38h0a891b7_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jinja2-time=0.2.0=pyhd8ed1ab_3
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py38h578d9bd_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - keyring=23.13.1=py38h578d9bd_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py38h43d8883_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lazy-object-proxy=1.9.0=py38h1de0b5d_0
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=16.0.4=default_h1cdf331_0
  - libclang13=16.0.4=default_h4d60ac6_0
  - libcups=2.3.3=h36d4200_3
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.12=h3358134_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.76.3=hebfc3b9_0
  - libgpg-error=1.46=h620e276_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm16=16.0.4=h5cf9203_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.3=hbcd7760_1
  - libsndfile=1.2.0=hb75c966_0
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=253=h8c4010b_1
  - libtiff=4.5.0=ha587672_6
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.3.0=hb47c5f0_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.5.0=h5d7e998_3
  - libxml2=2.11.4=h0d562d8_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=16.0.4=h4dfa4b3_0
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=2.1.2=py38h1de0b5d_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - more-itertools=9.1.0=pyhd8ed1ab_0
  - mpg123=1.31.3=hcb278e6_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.0.32=hf1915f5_2
  - mysql-libs=8.0.32=hca2cd23_2
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.4.0=pyhd8ed1ab_0
  - nbconvert-core=7.4.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.4.0=pyhd8ed1ab_0
  - nbformat=5.9.0=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numpy=1.24.3=py38h59b608b_0
  - numpydoc=1.5.0=pyhd8ed1ab_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.1=hd590300_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.2=py38h01efb38_0
  - pandoc=2.19.2=h32600fe_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.11.1=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py38h885162f_1
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - prompt-toolkit=3.0.38=pyha770c72_0
  - psutil=5.9.5=py38h1de0b5d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio-client=16.1=hb77b528_4
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycairo=1.23.0=py38h190342e_0
  - pycodestyle=2.10.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_0
  - pyflakes=3.0.1=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pylint=2.17.4=pyhd8ed1ab_0
  - pylint-venv=3.0.1=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py38ha0d8c90_3
  - pyqt5-sip=12.11.0=py38h8dc9893_3
  - pyqtwebengine=5.15.7=py38h2cd9a72_3
  - pyrsistent=0.19.3=py38h1de0b5d_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.16=he550d4f_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-lsp-black=1.3.0=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.0.0=pyhd8ed1ab_0
  - python-lsp-server=1.7.3=pyhd8ed1ab_0
  - python-lsp-server-base=1.7.3=pyhd8ed1ab_0
  - python-slugify=8.0.1=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytoolconfig=1.2.5=pyhd8ed1ab_0
  - pytz=2023.3=pyhd8ed1ab_0
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_5
  - pyzmq=25.1.0=py38h509eb50_0
  - qdarkstyle=3.1=pyhd8ed1ab_0
  - qstylizer=0.2.2=pyhd8ed1ab_0
  - qt-main=5.15.8=h01ceb2d_12
  - qt-webengine=5.15.8=h27f4a20_2
  - qtawesome=1.2.3=pyhd8ed1ab_0
  - qtconsole=5.4.3=pyhd8ed1ab_0
  - qtconsole-base=5.4.3=pyha770c72_0
  - qtpy=2.3.1=pyhd8ed1ab_0
  - rdkit=2023.03.1=py38h36d2b2f_0
  - readline=8.2=h5eee18b_0
  - reportlab=3.6.13=py38h57c54bf_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rope=1.8.0=pyhd8ed1ab_0
  - rtree=1.0.1=py38h02d302b_1
  - secretstorage=3.3.3=py38h578d9bd_1
  - setuptools=67.8.0=py38h06a4308_0
  - sip=6.7.9=py38h17151c0_0
  - six=1.16.0=pyh6c4a22f_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sphinx=7.0.1=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - spyder=5.4.3=py38h578d9bd_0
  - spyder-kernels=2.4.3=unix_pyhd8ed1ab_0
  - sqlalchemy=2.0.15=py38h01eb140_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - text-unidecode=1.3=py_0
  - textdistance=4.5.0=pyhd8ed1ab_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.8=pyha770c72_0
  - tornado=6.3.2=py38h01eb140_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.6.2=hd8ed1ab_0
  - typing_extensions=4.6.2=pyha770c72_0
  - ujson=5.7.0=py38h8dc9893_0
  - unicodedata2=15.0.0=py38h0a891b7_0
  - unidecode=1.3.6=pyhd8ed1ab_0
  - urllib3=2.0.2=pyhd8ed1ab_0
  - watchdog=3.0.0=py38h578d9bd_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - whatthepatch=1.0.5=pyhd8ed1ab_0
  - wheel=0.38.4=py38h06a4308_0
  - wrapt=1.15.0=py38h1de0b5d_0
  - wurlitzer=3.0.3=pyhd8ed1ab_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-compositeproto=0.4.2=h7f98852_1001
  - xorg-damageproto=1.2.1=h7f98852_1002
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h8ee46fc_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-util-macros=1.19.3=h7f98852_0
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yapf=0.33.0=pyhd8ed1ab_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - anyio==3.7.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - autograd==1.5
    - configspace==0.7.1
    - dask==2023.5.0
    - dask-jobqueue==0.8.2
    - dataclasses==0.6
    - distributed==2023.5.0
    - emcee==3.1.4
    - exceptiongroup==1.1.1
    - filelock==3.13.1
    - findiff==0.9.2
    - fqdn==1.5.1
    - fsspec==2023.6.0
    - future==0.18.3
    - fuzzywuzzy==0.18.0
    - huggingface-hub==0.20.2
    - isoduration==20.11.0
    - jax==0.4.12
    - jaxlib==0.4.12
    - joblib==1.2.0
    - jsonpointer==2.3
    - jupyter-events==0.6.3
    - jupyter-server==2.6.0
    - jupyter-server-terminals==0.4.4
    - lightgbm==3.3.5
    - locket==1.0.0
    - matplotlib==3.7.4
    - ml-dtypes==0.2.0
    - mpmath==1.3.0
    - msgpack==1.0.5
    - nbclassic==1.0.0
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numdifftools==0.9.41
    - opt-einsum==3.3.0
    - overrides==7.3.1
    - partd==1.4.0
    - pip==23.1.2
    - prometheus-client==0.17.0
    - pynisher==1.0.5
    - pyrfr==0.9.0
    - pytdc==0.4.1
    - python-json-logger==2.0.7
    - rdkit-pypi==2022.9.5
    - regex==2023.6.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.13.1
    - send2trash==1.8.2
    - smac==2.0.1
    - sniffio==1.3.0
    - sympy==1.12
    - tblib==1.7.0
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - toolz==0.12.0
    - tqdm==4.66.1
    - uri-template==1.2.0
    - webcolors==1.13
    - websocket-client==1.5.2
    - zict==3.0.0
prefix: /home/dahvida/anaconda3/envs/lightning
